apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-journal-local
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/plasterinho/ops-journal.git'
    targetRevision: HEAD
    path: environments/local

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true