apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-journal-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/plasterinho/ops-journal.git
    targetRevision: HEAD
    path: workloads/ops-journal/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
