server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'OK';
    }

    location = /monitor/version {
        default_type application/json;
        # For development, we can return a static version. In production,
        # we serve the generated JSON file.
        # return 200 '{"version": "dev"}';
        # try_files monitor_version.json =404;
        alias /usr/share/nginx/html/monitor_version.json;
    }
}