name: Build and Push Images

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set image tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "image_tag=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Build main app image ---
      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.image_tag }}

      # --- Build metrics image ---
      - name: Build and push metrics image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./metrics/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-metrics:${{ steps.vars.outputs.image_tag }}

  promote:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v5
        with:
          repository: plasterinho/cluster-config
          token: ${{ secrets.PBOT_INFRA_TOKEN }}
          path: cluster-config

      - name: Update image tag
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image_tag }}

          INFRA_PATH="cluster-config/gitops/apps/ops-journal/overlays/dev/kustomization.yaml"

          sed -i "s/newTag: .*/newTag: ${IMAGE_TAG}/" "${INFRA_PATH}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PBOT_INFRA_TOKEN }}
          path: cluster-config
          commit-message: "chore: deploy ${{ needs.build.outputs.image_tag }}"
          branch: deploy-${{ github.sha }}
          title: "Deploy ${{ needs.build.outputs.image_tag }}"
          body: "Automated deployment of image ${{ needs.build.outputs.image_tag }}."
          base: main
          labels: deployment
          